name: build

on:
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  linux:
    name: build for linux
    runs-on: ubuntu-20.04
     
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install (Linux)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib make

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Setting up ambuild
        run: |
          python -m pip install wheel
          pip install git+https://github.com/accelerator74/ambuild
          
      - name: Getting hl2sdk-l4d2
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: hl2sdk-l4d2

      - name: Checking out MM:Source
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: metamod-master

      - name: Checking out own repository
        uses: actions/checkout@v3
        with:
          path: src

      - name: Compiling ${{ github.event.repository.name }} files
        working-directory: src
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize --sdks="l4d2" --mms-path="${{ github.workspace }}/metamod-metamod-master"
          ambuild
